# Generated by Django 5.2.8 on 2025-11-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.TextField(blank=True, verbose_name='Товары в заказе'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
