# Generated by Django 5.2.8 on 2025-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_order_delivery_cost_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
