# Generated by Django 6.0.4 on 2026-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('file', models.FileField(upload_to='music/', verbose_name='MP3 файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок воспроизведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Музыкальный трек',
                'verbose_name_plural': 'Музыкальные треки',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
